//! Authoritative content for the README rule tables (Issue #257).
//!
//! Rows are declared in README display order, grouped by table: `Rules` (28),
//! then `Security` (2), then `AstSecurity` (16). `severity` is shared by both
//! languages; the `*_ja` fields hold the README.ja.md prose (a separate human
//! translation, not a literal mirror). Severity / description / why are migrated
//! verbatim from the README cells; `why` and `when_to_disable` are
//! human-authored prose, kept as data so the generator never invents them.
//! Edit here, then run `cargo test bless_readme_rule_tables -- --ignored`.

use super::{RuleDoc, Table};
use crate::rules::rule_id;

pub(super) static RULE_DOCS: &[RuleDoc] = &[
    // ----- ### Rules (toggle-level, 5 columns) -----
    RuleDoc {
        table: Table::Rules,
        key: "sensitiveFile",
        rule_id: Some(rule_id::SENSITIVE_FILE),
        severity: "Critical",
        description: r"Blocks writes to .env, credentials.\*, \*.pem",
        why: r"Committed credentials persist in git history and CI logs and have to be rotated to revoke",
        when_to_disable: Some("Never (security critical)"),
        description_ja: r".env、credentials.\*、\*.pem への書き込みをブロック",
        why_ja: r"一度コミットすると git 履歴と CI ログに永続化し、無効化にはローテートが必要になる",
        when_to_disable_ja: Some("無効化不可（セキュリティ上重要）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "cryptoWeak",
        rule_id: Some(rule_id::CRYPTO_WEAK),
        severity: "High",
        description: r"Detects MD5, SHA1, DES, RC4 usage",
        why: r"Collisions and key recovery are feasible; the primitive cannot deliver the guarantee it promises",
        when_to_disable: Some("Legacy system maintenance with known constraints"),
        description_ja: r"MD5、SHA1、DES、RC4 の使用を検出",
        why_ja: r"衝突攻撃や鍵回復が現実的で、プリミティブ自体が約束した保証を提供できない",
        when_to_disable_ja: Some("既知の制約があるレガシーシステムの保守"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "sensitiveLogging",
        rule_id: Some(rule_id::SENSITIVE_LOGGING),
        severity: "High",
        description: r"Detects password/token/secret in console.log",
        why: r"Logs flow into CI runners, monitoring sinks, and crash reporters, so every downstream reader sees the secret",
        when_to_disable: Some("Never (security critical)"),
        description_ja: r"console.log 内の password/token/secret を検出",
        why_ja: r"ログは CI runner / 監視 sink / クラッシュレポータに流れ、下流の全ての読み手にシークレットが届く",
        when_to_disable_ja: Some("無効化不可（セキュリティ上重要）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "security",
        rule_id: None,
        severity: "Mixed",
        description: r"XSS vectors, unsafe APIs, sensitive storage. See `Security Rules` below for the rule_id breakdown",
        why: r"Each pattern is either an eval sink or origin-readable storage, so any script on the page can exfiltrate state",
        when_to_disable: Some("Never (security critical)"),
        description_ja: r"XSS ベクター、安全でない API、機密ストレージ。rule_id 別の内訳は下記の `Security Rules` を参照",
        why_ja: r"各パターンが eval sink もしくは origin から読み取れる storage で、同一オリジンの任意スクリプトが state を抜ける",
        when_to_disable_ja: Some("無効化不可（セキュリティ上重要）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "architecture",
        rule_id: Some(rule_id::ARCHITECTURE),
        severity: "High",
        description: r"Layer violations (e.g., UI importing domain)",
        why: r"Once a UI file reaches into domain internals, the boundary stops constraining future change and refactors stall",
        when_to_disable: Some("Small projects, monoliths, or scripts"),
        description_ja: r"レイヤー違反（例: UI がドメインをインポート）",
        why_ja: r"UI がドメイン内部に到達すると境界が将来の変更を制約しなくなり、refactor が止まる",
        when_to_disable_ja: Some("小規模プロジェクト、モノリス、スクリプト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "eval",
        rule_id: Some(rule_id::EVAL),
        severity: "High",
        description: r"eval(), new Function(), indirect eval",
        why: r"Whatever string lands there runs as code, so tainted input becomes arbitrary execution",
        when_to_disable: Some("Never (security critical)"),
        description_ja: r"eval()、new Function()、間接的 eval",
        why_ja: r"そこに到達した文字列はそのままコードとして走るので、汚染入力が任意コード実行に化ける",
        when_to_disable_ja: Some("無効化不可（セキュリティ上重要）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "hardcodedSecrets",
        rule_id: Some(rule_id::HARDCODED_SECRET),
        severity: "High",
        description: r"API keys, tokens, passwords in source",
        why: r"The key is public the moment the repo is pushed; rotation is the only remediation",
        when_to_disable: Some("Never (security critical)"),
        description_ja: r"ソースコード内の API キー、トークン、パスワード",
        why_ja: r"リポジトリを push した瞬間にキーは公開され、ローテート以外に対処手段が無い",
        when_to_disable_ja: Some("無効化不可（セキュリティ上重要）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "cotLeakageMarker",
        rule_id: Some(rule_id::COT_LEAKAGE_MARKER),
        severity: "High",
        // Both descriptions are split via concat! so no single source line holds
        // a literal CoT marker: guardrails' own cot-leakage-marker rule scans
        // every file line-by-line and self-excludes only cot_leakage_marker.rs.
        // The concatenated values are the verbatim README cells. The channel /
        // start markers carry a markdown-escape backslash, so they never match
        // the rule and need no split.
        description: concat!(
            r"AI chain-of-thought leak markers (`<",
            r"thinking>`, `<\|channel\|>`, `<\|start\|>assistant`, `to=",
            r"functions.`)"
        ),
        why: r"Model internal state ships into production traces, UI, or documentation when these tags survive copy-paste",
        when_to_disable: Some("Projects that intentionally persist AI traces / transcripts"),
        description_ja: concat!(
            r"AI Chain-of-Thought リークマーカー (`<",
            r"thinking>`、`<\|channel\|>`、`<\|start\|>assistant`、`to=",
            r"functions.`)"
        ),
        why_ja: r"コピペで生き残ったタグごと、モデル内部状態が本番ログ / UI / ドキュメントに流出する",
        when_to_disable_ja: Some("AI トレース/トランスクリプトを意図的に保存するプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "openRedirect",
        rule_id: Some(rule_id::OPEN_REDIRECT),
        severity: "High",
        description: r"location.href/assign with user-controlled input",
        why: r"The attacker chooses the destination while the URL still wears your origin, the ideal phishing setup",
        when_to_disable: Some("Non-web projects"),
        description_ja: r"ユーザー制御入力による location.href/assign",
        why_ja: r"攻撃者が遷移先を選べるのに URL は自オリジンを纏ったままで、フィッシングの理想形になる",
        when_to_disable_ja: Some("Web 以外のプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "rawHtml",
        rule_id: Some(rule_id::RAW_HTML),
        severity: "High",
        description: r"HTML concatenation with variables",
        why: r"String-concat HTML places attacker input directly into the live DOM, an XSS sink",
        when_to_disable: Some("Non-web projects"),
        description_ja: r"変数を含む HTML の文字列結合",
        why_ja: r"文字列結合 HTML は攻撃者入力をそのまま live DOM に置く XSS sink",
        when_to_disable_ja: Some("Web 以外のプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "sqliConcat",
        rule_id: Some(rule_id::SQLI_CONCAT),
        severity: "High",
        description: r"SQL assembled via template interpolation or string concatenation",
        why: r"Interpolated SQL splices user input into the query body, the classic SQL injection",
        when_to_disable: Some("Projects without database access"),
        description_ja: r"テンプレートリテラル/文字列結合で組み立てた SQL を検出",
        why_ja: r"補間 SQL はユーザー入力をクエリ本体に混入させる、典型的な SQL injection",
        when_to_disable_ja: Some("データベースを使用しないプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "httpResource",
        rule_id: Some(rule_id::HTTP_RESOURCE),
        severity: "Medium",
        description: r"HTTP (non-HTTPS) resource URLs",
        why: r"Non-TLS resources let on-path attackers swap content (mixed-content downgrade, supply-chain tampering)",
        when_to_disable: Some("Development-only configs"),
        description_ja: r"HTTP（非 HTTPS）リソース URL",
        why_ja: r"非 TLS リソースは on-path 攻撃者が中身を差し替えられる（mixed-content downgrade、サプライチェーン改竄）",
        when_to_disable_ja: Some("開発専用の設定"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "corsWildcard",
        rule_id: Some(rule_id::CORS_WILDCARD),
        severity: "Medium",
        description: r"CORS wildcard origin (`cors({ origin: '*' })`, `Access-Control-Allow-Origin: *`). Scoped to `app/api/`, `pages/api/`, and `middleware.{ts,js}`",
        why: r"`*` lets any origin read the response, dropping the same-origin policy that protects user data",
        when_to_disable: Some("Rarely needed (scope already excludes UI/util files)"),
        description_ja: r"CORS ワイルドカード origin (`cors({ origin: '*' })`、`Access-Control-Allow-Origin: *`)",
        why_ja: r"`*` は任意オリジンに応答を読ませ、ユーザーデータを守る same-origin policy を外す",
        when_to_disable_ja: Some("Web 以外のプロジェクト、社内 API 専用"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "transaction",
        rule_id: Some(rule_id::TRANSACTION_BOUNDARY),
        severity: "Medium",
        description: r"Multiple writes without transaction wrapper. Scoped to `usecases/`, `use-cases/`, `application/`, `services/`, `domain/`, `handlers/`, `app/`, `server/` directories and `app/**/route.{ts,js}` segments",
        why: r"A failure between writes leaves partial state behind: orphan rows, balance drift, inconsistent invariants",
        when_to_disable: Some(
            "Non-database projects, or layout that does not use these directory names",
        ),
        description_ja: r"トランザクションラッパーなしの複数書き込み。スコープは `usecases/`、`use-cases/`、`application/`、`services/`、`domain/`、`handlers/`、`app/`、`server/` ディレクトリと `app/**/route.{ts,js}` セグメント",
        why_ja: r"書き込み途中で失敗すると部分状態が残る: 孤児レコード、残高ずれ、不変条件の崩れ",
        when_to_disable_ja: Some("データベースを使用しないプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "domAccess",
        rule_id: Some(rule_id::DOM_ACCESS),
        severity: "Medium",
        description: r"Direct DOM manipulation in React (.tsx/.jsx)",
        why: r"Imperative DOM mutations race the React reconciler; invariants break with no warning and bugs reproduce only intermittently",
        when_to_disable: Some("Non-React projects, or vanilla JS/TS"),
        description_ja: r"React（.tsx/.jsx）での直接 DOM 操作",
        why_ja: r"命令的 DOM 操作は React の reconciler と競合し、不変条件が崩れて再現性の低いバグになる",
        when_to_disable_ja: Some("React 以外のプロジェクト、またはバニラ JS/TS"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "syncIo",
        rule_id: Some(rule_id::SYNC_IO),
        severity: "Medium",
        description: r"readFileSync, writeFileSync (blocks event loop)",
        why: r"A single sync I/O call freezes the event loop, so every concurrent request stalls behind it",
        when_to_disable: Some("CLI tools, build scripts, or sync-only contexts"),
        description_ja: r"readFileSync、writeFileSync（イベントループをブロック）",
        why_ja: r"一回の同期 I/O が event loop を凍結し、並行リクエストが全てそこで詰まる",
        when_to_disable_ja: Some("CLI ツール、ビルドスクリプト、同期のみのコンテキスト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "bundleSize",
        rule_id: Some(rule_id::BUNDLE_SIZE),
        severity: "Medium",
        description: r"Full lodash/moment imports",
        why: r"A full `lodash` or `moment` import ships hundreds of KB to every visitor for a few utility functions",
        when_to_disable: Some("Backend/Node.js (no bundle size concerns)"),
        description_ja: r"lodash/moment のフルインポート",
        why_ja: r"`lodash` / `moment` を丸ごとインポートすると、数個の utility のために数百 KB が全訪問者に届く",
        when_to_disable_ja: Some("バックエンド/Node.js（バンドルサイズの懸念なし）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "testAssertion",
        rule_id: Some(rule_id::TEST_ASSERTION),
        severity: "Medium",
        description: r"Tests with no assertion, or only weak/mock/self-equal ones",
        why: r"An assertion that holds for any output (none, only toBeTruthy/toBeDefined, only toHaveBeenCalled, or expect(x).toBe(x)) lets green CI hide the regression",
        when_to_disable: Some("Playwright, custom test frameworks"),
        description_ja: r"表明が無い、または弱い表明・モック呼び出しのみ・自明な恒真のテスト",
        why_ja: r"どんな出力でも通る表明（無し・toBeTruthy/toBeDefined のみ・toHaveBeenCalled のみ・expect(x).toBe(x)）は CI を green にして回帰を隠す",
        when_to_disable_ja: Some("Playwright、カスタムテストフレームワーク"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "flakyTest",
        rule_id: Some(rule_id::FLAKY_TEST),
        severity: "Low",
        description: r"setTimeout, Math.random in tests",
        why: r"Time and RNG make failures non-deterministic, so people retry instead of investigating",
        when_to_disable: Some("Intentional timing/randomness tests"),
        description_ja: r"テスト内の setTimeout、Math.random",
        why_ja: r"時刻と RNG で失敗が非決定的になり、原因究明より retry が選ばれて CI シグナルが劣化する",
        when_to_disable_ja: Some("意図的なタイミング/ランダムネスのテスト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "generatedFile",
        rule_id: Some(rule_id::GENERATED_FILE),
        severity: "High",
        description: r"Warns on \*.generated.\*, \*.g.ts edits",
        why: r"Hand edits are overwritten on the next generation, so the fix disappears on the next run",
        when_to_disable: Some("No code generation in project"),
        description_ja: r"\*.generated.\*、\*.g.ts の編集を警告",
        why_ja: r"手編集は次回生成で上書きされ、修正が消える",
        when_to_disable_ja: Some("コード生成のないプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "testLocation",
        rule_id: Some(rule_id::TEST_LOCATION),
        severity: "Medium",
        description: r"Test files in src/ directory",
        why: r"Tests under `src/` reach the production bundle when build excludes do not catch them",
        when_to_disable: Some("Co-located test strategy (tests next to source)"),
        description_ja: r"src/ ディレクトリ内のテストファイル",
        why_ja: r"`src/` 配下のテストは build 除外漏れで本番バンドルに混入する",
        when_to_disable_ja: Some("コロケーションテスト戦略（ソースと同じ場所）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "naming",
        rule_id: Some(rule_id::NAMING_CONVENTION),
        severity: "Mixed",
        description: r"Naming conventions. Medium for components; Low for interfaces and types, so this rule never blocks under the default threshold",
        why: r"Inconsistent PascalCase defeats code search and the pattern recognition that picks these out",
        when_to_disable: Some("Different naming conventions in team/project"),
        description_ja: r"命名規則。コンポーネントは Medium、interface と型は Low なので、default の閾値ではこの rule は編集を止めない",
        why_ja: r"PascalCase が一貫しないと code search と、それらを識別するパターン認識を破壊する",
        when_to_disable_ja: Some("チーム/プロジェクトで異なる命名規則がある場合"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "noUseEffect",
        rule_id: Some(rule_id::NO_USE_EFFECT),
        severity: "Medium",
        description: r"Flags useEffect in .tsx/.jsx with alternative suggestions",
        why: r"`useEffect` for derivable state triggers extra renders and the dependency array becomes a stale-data trap",
        when_to_disable: Some("Projects using useEffect intentionally"),
        description_ja: r".tsx/.jsx内のuseEffectを検出し代替案を提示",
        why_ja: r"派生 state に対する `useEffect` は余分な再 render を生み、依存配列が stale-data の罠になる",
        when_to_disable_ja: Some("useEffectを意図的に使用するプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "serviceWorker",
        rule_id: Some(rule_id::SERVICE_WORKER_SCOPE_ROOT),
        severity: "Medium",
        description: r"Service Worker registration with root scope (`{ scope: '/' }`). Suggests narrowing to a specific path",
        why: r"Root scope intercepts every navigation on the origin, so one misregistration hijacks the whole site",
        when_to_disable: Some("Projects intentionally serving the worker site-wide"),
        description_ja: r"ルートスコープ（`{ scope: '/' }`）での Service Worker 登録。特定パスへのスコープ絞り込みを提案",
        why_ja: r"ルートスコープはオリジンの全 navigation を傍受するので、一度の誤登録でサイト全体を乗っ取られる",
        when_to_disable_ja: Some("サイト全体に worker を意図的に配信するプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "jwtClient",
        rule_id: Some(rule_id::JWT_CLIENT_DECODE),
        severity: "Medium",
        description: r"Client-side JWT decode (`jwtDecode`, `jwt_decode`, `atob(token.split('.'))`). Suggests server-side `jwtVerify`",
        why: r"JWT payload is base64url. It is readable but also editable without a signature check, so trusting it on the client is an authorization bypass",
        when_to_disable: Some("Server-only JWT decode paths (e.g., Node-only files)"),
        description_ja: r"クライアント側 JWT デコード（`jwtDecode`、`jwt_decode`、`atob(token.split('.'))`）。サーバー側 `jwtVerify` を推奨",
        why_ja: r"JWT payload は base64url で読めるが、署名検証なしには改竄も通る。クライアントで信用すると認可回避になる",
        when_to_disable_ja: Some("サーバー専用 JWT デコード経路（Node 専用ファイル等）"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "astSecurity",
        rule_id: None,
        severity: "Mixed",
        description: r"AST-based: command/regex/require injection, stack exposure, path traversal, prototype pollution, bidi chars, env-var fallback, insecure RNG, unsafe HTML injection, client env leak, SSR secret bleed, postMessage origin (see below)",
        why: r"Aggregated AST checks. Each sub-rule has its own threat (see the sub-rule table below)",
        when_to_disable: Some("Non-Node.js projects"),
        description_ja: r"ASTベース: コマンド/正規表現/require インジェクション、スタック露出、パストラバーサル、プロトタイプ汚染、bidi 文字、env-var フォールバック、不安全な乱数、HTML インジェクション、client env leak、SSR secret bleed、postMessage origin（下記参照）",
        why_ja: r"AST ベースの集約。各 sub-rule にそれぞれの脅威がある（下記 sub-rule 表を参照）",
        when_to_disable_ja: Some("Node.js以外のプロジェクト"),
    },
    RuleDoc {
        table: Table::Rules,
        key: "invariant",
        rule_id: None,
        severity: "Mixed",
        description: r"Pinned-value gate: blocks an edit that drifts a `.json` value away from its pinned scalar, and an edit to `.invariants.json` itself that weakens a pin (see below)",
        why: r"Two rule_ids under one toggle. Each has its own threat (see the sub-rule table below)",
        when_to_disable: Some(
            "Projects that do not pin invariant values. Deletion is out of reach either way: guardrails inspects only Write/Edit/MultiEdit tool input, so `rm .invariants.json` reaches no hook",
        ),
        description_ja: r"固定値ゲート: `.invariants.json` で固定したスカラー値から `.json` の値がずれる編集と、`.invariants.json` 自体の pin を弱める編集をブロック（下記参照）",
        why_ja: r"1 つの toggle に 2 つの rule_id がある。それぞれに脅威がある（下記 sub-rule 表を参照）",
        when_to_disable_ja: Some(
            "不変値を固定しないプロジェクト。削除はどちらの rule でも届かない: guardrails は Write/Edit/MultiEdit の tool input のみを見るため、`rm .invariants.json` はどの hook にも届かない",
        ),
    },
    RuleDoc {
        table: Table::Invariant,
        key: "invariant",
        rule_id: Some(rule_id::INVARIANT),
        severity: "High",
        description: r"Blocks an edit that drifts a `.json` value away from the scalar pinned for it in `.invariants.json` (feature flags, i18n strings, design tokens)",
        why: r"A pinned value is a contract the rest of the app depends on; a silent edit that changes it ships a behavior change no human approved",
        when_to_disable: None,
        description_ja: r"`.invariants.json` で固定したスカラー値から `.json` の値がずれる編集をブロック（feature flag、i18n 文言、design token）",
        why_ja: r"固定値はアプリ全体が依存する契約で、無言で変える編集は誰も承認していない挙動変更を出荷する",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::Invariant,
        key: "invariant-guard",
        rule_id: Some(rule_id::INVARIANT_GUARD),
        severity: "Critical",
        description: r"Blocks an edit to `.invariants.json` itself that drops a declared pin or changes its declared value, independent of the drift check above",
        why: r"An agent that can rewrite the declaration file can weaken the very pin meant to stop it, bypassing the drift check without touching the file the pin protects",
        when_to_disable: None,
        description_ja: r"`.invariants.json` 自体への編集が宣言済み pin を落とす、または宣言値を変えるものであれば、上記のドリフト検知とは独立にブロック",
        why_ja: r"宣言ファイルを書き換えられる agent は、pin が守ろうとしているファイルに触れずに pin 自体を弱められる。上記のドリフト検知はこれを検出できない",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::Rules,
        key: "configGuard",
        rule_id: Some(rule_id::CONFIG_GUARD),
        severity: "Critical",
        description: r"Blocks an edit to the config files guardrails reads at the git root (`.guardrails.json`, `.claude/tools.json`, `.claude-guardrails.json`)",
        why: r"An agent that rewrites the config can switch off the rule that would stop its next edit, and an `overrides` entry reads as a test-path exclusion in the diff",
        when_to_disable: Some(
            "Repositories where an agent is expected to set up the config and a human cannot",
        ),
        description_ja: r"guardrails が git root で読む設定ファイル（`.guardrails.json`、`.claude/tools.json`、`.claude-guardrails.json`）への編集をブロック",
        why_ja: r"設定を書き換えられる agent は次の編集を止める rule を自分で切れる。`overrides` の追記は diff 上 test パスの除外に見える",
        when_to_disable_ja: Some("設定の用意を agent に任せ、人が用意できないリポジトリ"),
    },
    // ----- ### Security Rules (`security`) (rule_id-level, 4 columns) -----
    RuleDoc {
        table: Table::Security,
        key: "security",
        rule_id: Some(rule_id::SECURITY),
        severity: "Mixed",
        description: r"`setTimeout('str')` / `setInterval('str')` / `postMessage(_, '*')` (High); sensitive `localStorage` / `sessionStorage` (Medium)",
        why: r"String timers behave like `eval`, wildcard `postMessage` broadcasts to any listener, and secrets in storage are reachable by any script on the origin",
        when_to_disable: None,
        description_ja: r"`setTimeout('str')` / `setInterval('str')` / `postMessage(_, '*')` (High)、機密 `localStorage` / `sessionStorage` (Medium)",
        why_ja: r"文字列引数のタイマーは eval と同等、wildcard `postMessage` は任意の listener にブロードキャスト、storage 内のシークレットはオリジン上の任意スクリプトから読める",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::Security,
        key: "dangerous-inner-html",
        rule_id: Some(rule_id::DANGEROUS_INNER_HTML),
        severity: "High",
        description: r"React `dangerouslySetInnerHTML={...}` (XSS sink, scoped to `.tsx` / `.jsx`)",
        why: r"Bypasses React's text escaping; a tainted variable lands as live DOM and runs the attacker's script",
        when_to_disable: None,
        description_ja: r"React の `dangerouslySetInnerHTML={...}`（XSS sink、`.tsx` / `.jsx` のみ対象）",
        why_ja: r"React のテキストエスケープを迂回し、汚染変数が live DOM になって攻撃者のスクリプトが走る",
        when_to_disable_ja: None,
    },
    // ----- ### AST Security Rules (`astSecurity`) (rule_id-level, 4 columns) -----
    RuleDoc {
        table: Table::AstSecurity,
        key: "child-process-injection",
        rule_id: Some(rule_id::CHILD_PROCESS_INJECTION),
        severity: "High",
        description: r"Non-literal args to exec/execSync/spawn/spawnSync. Scoped to `app/api/`, `pages/api/`, and files with `'use server'` directive",
        why: r"An untrusted segment becomes a shell command, so the request author runs arbitrary processes on the server",
        when_to_disable: None,
        description_ja: r"exec/execSync/spawn/spawnSync への非リテラル引数",
        why_ja: r"信頼できないセグメントが shell コマンドに化け、リクエスト送信者がサーバー上で任意プロセスを起動できる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "err-stack-exposure",
        rule_id: Some(rule_id::ERR_STACK_EXPOSURE),
        severity: "High",
        description: r"Error stack traces leaked in HTTP responses (res.json/res.send). Scoped to `app/api/`, `pages/api/`, and `app/**/route.{ts,js}` segments",
        why: r"Stacks reveal file paths, library versions, and hosting layout, providing recon fuel for the next exploitation step",
        when_to_disable: None,
        description_ja: r"HTTP レスポンス（res.json/res.send）でのエラースタックトレース漏洩",
        why_ja: r"スタックでファイルパス・ライブラリバージョン・ホスティング構成が露出し、次の攻撃ステップの偵察材料になる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "non-literal-fs-path",
        rule_id: Some(rule_id::NON_LITERAL_FS_PATH),
        severity: "Medium",
        description: r"Non-literal file paths in fs.\* calls (path traversal risk). Scoped to `app/api/`, `pages/api/`, and files with `'use server'` directive",
        why: r"`..` segments slip past the intended root, exposing arbitrary files for read or overwrite",
        when_to_disable: None,
        description_ja: r"fs.\* 呼び出しでの非リテラルファイルパス（パストラバーサルリスク）",
        why_ja: r"`..` セグメントが意図したルートを越えて、任意ファイルを read / overwrite できるようになる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "non-literal-require",
        rule_id: Some(rule_id::NON_LITERAL_REQUIRE),
        severity: "Medium",
        description: r"Non-literal arg to require() (dynamic module loading). Scoped to `app/api/`, `pages/api/`, and files with `'use server'` directive",
        why: r"A tainted module name loads attacker-controlled JavaScript into the running process",
        when_to_disable: None,
        description_ja: r"require() への非リテラル引数（動的モジュールロード）",
        why_ja: r"汚染されたモジュール名で攻撃者制御の JavaScript を実行中プロセスにロードする",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "unsafe-regex",
        rule_id: Some(rule_id::UNSAFE_REGEX),
        severity: "Medium",
        description: r"Regex literals vulnerable to ReDoS (nested quantifiers, catastrophic backtracking)",
        why: r"A crafted input drives the engine into exponential backtracking. CPU hits 100% and the server stops serving others",
        when_to_disable: None,
        description_ja: r"ReDoS に脆弱な正規表現リテラル（ネストされた量指定子、catastrophic backtracking）",
        why_ja: r"細工した入力でエンジンが指数バックトラックに陥り、CPU が 100% になって他のリクエストに応答できなくなる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "bidi-characters",
        rule_id: Some(rule_id::BIDI_CHARACTERS),
        severity: "High",
        description: r"Unicode bidirectional control chars hidden in source (CVE-2021-42574 / Trojan Source)",
        why: r"Bidi chars reorder source at render time, so reviewers see different code than the compiler, and malicious logic hides in plain sight",
        when_to_disable: None,
        description_ja: r"ソース中に潜む Unicode 双方向制御文字（CVE-2021-42574 / Trojan Source）",
        why_ja: r"bidi 文字は描画時にソースを並べ替えるので、レビュワーが見るコードとコンパイラが見るコードが食い違い、悪意あるロジックが平然と隠れる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "excessive-nesting",
        rule_id: Some(rule_id::EXCESSIVE_NESTING),
        severity: "High",
        description: r"Source nested past a safe depth — `()[]{}` brackets or `!`/`~` prefix runs",
        why: r"Deeply nested input overflows the parser's recursion and crashes the check process before any rule runs, which would silently let the edit through; a byte scan blocks it before the parse",
        when_to_disable: None,
        description_ja: r"安全な深さを超えた入れ子 — `()[]{}` 括弧または `!`/`~` の連鎖",
        why_ja: r"深い入れ子はパーサの再帰をオーバーフローさせ、ルール実行前にチェックプロセスを落とし、編集が黙って通ってしまう。パース前のバイトスキャンで阻止する",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "ast-checker-internal-failure",
        rule_id: Some(rule_id::AST_CHECKER_INTERNAL_FAILURE),
        severity: "High",
        description: r"AST checker subprocess failed before completing every structural rule",
        why: r"An incomplete checker run cannot establish that the edit is safe; blocking prevents an internal failure from silently bypassing structural rules",
        when_to_disable: None,
        description_ja: r"AST checker subprocess が structural rule の完了前に内部失敗した場合にブロック",
        why_ja: r"未完了の検査では編集の安全性を確認できないため、内部失敗による structural rule の黙った迂回をブロックする",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "env-var-fallback",
        rule_id: Some(rule_id::ENV_VAR_FALLBACK),
        severity: "High",
        description: r"`process.env.X \|\| 'default'` style — leaks secrets via hardcoded fallback",
        why: r"When the env var is unset, the hardcoded default ships as the real credential, and stays in source forever",
        when_to_disable: None,
        description_ja: r"`process.env.X \|\| 'default'` 形式 — ハードコードされたフォールバックでシークレットが漏洩する",
        why_ja: r"env var が未設定だとハードコードされたデフォルトが本物の credential として動き、しかもソース内に永遠に残る",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "test-endpoint-prod-guard",
        rule_id: Some(rule_id::TEST_ENDPOINT_PROD_GUARD),
        severity: "Medium",
        description: r"Test-named route file (`app/api/test-*/route.ts`, `pages/api/seed.ts`, …) with no `process.env.NODE_ENV === 'production'` guard in the file",
        why: r"A test-only endpoint shipped without a production guard exposes data seeding, deletion, or debug surfaces in production; this advisory prompts an in-file guard, or confirmation the route is excluded another way",
        when_to_disable: None,
        description_ja: r"本番ガード (`process.env.NODE_ENV === 'production'`) を持たないテスト用ルートファイル (`app/api/test-*/route.ts`、`pages/api/seed.ts` など)",
        why_ja: r"本番ガード無しのテスト専用エンドポイントは本番でデータ投入・削除・デバッグ面を露出させる。同一ファイル内のガード追加か他経路での除外確認を促す advisory",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "prototype-pollution",
        rule_id: Some(rule_id::PROTOTYPE_POLLUTION),
        severity: "High",
        description: r"`Object.assign({}, untrusted)`, `_.merge`, `Object.create` with `__proto__`/`constructor`",
        why: r"Writes to `__proto__` taint every object in the runtime. Auth checks misfire and, depending on the downstream sink, code execution opens",
        when_to_disable: None,
        description_ja: r"`Object.assign({}, untrusted)`、`_.merge`、`__proto__`/`constructor` を伴う `Object.create`",
        why_ja: r"`__proto__` への書き込みがランタイム上の全オブジェクトを汚染し、認可チェックが誤動作し、sink 次第ではコード実行も開く",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "math-random-insecure",
        rule_id: Some(rule_id::MATH_RANDOM_INSECURE),
        severity: "Mixed",
        description: r"`Math.random()` in token/ID/secret contexts. High when usage is concrete (`toString(36)` idiom or crypto-API argument); Medium when only inferable from naming heuristics (security-named var/fn, other `toString` radix). See [ADR-0003](docs/decisions/0003-math-random-severity-policy.md).",
        why: r"`Math.random` is predictable; tokens minted from it can be guessed and sessions hijacked",
        when_to_disable: None,
        description_ja: r"トークン/ID/シークレット用途の `Math.random()`。用法が確定する場合（`toString(36)` イディオム / 暗号 API 引数）は High、命名ヒューリスティック（security 系の変数名・関数名、`toString` 他基数）止まりは Medium。詳細は [ADR-0003](docs/decisions/0003-math-random-severity-policy.md)",
        why_ja: r"`Math.random` は予測可能で、これで作ったトークンは推測されセッションがハイジャックされうる",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "unsafe-html-injection",
        rule_id: Some(rule_id::UNSAFE_HTML_INJECTION),
        severity: "Mixed",
        description: r"Non-literal assignment to `innerHTML` (High) / `outerHTML` (Medium) / `document.write[ln]` (High). See [ADR-0008](docs/decisions/0008-unsafe-html-injection-rule-id-separation.md).",
        why: r"A tainted value reaches an HTML sink, and the parser runs whatever script tags it finds. XSS at the DOM layer",
        when_to_disable: None,
        description_ja: r"`innerHTML`（High）/ `outerHTML`（Medium）/ `document.write[ln]`（High）への非リテラル代入。詳細は [ADR-0008](docs/decisions/0008-unsafe-html-injection-rule-id-separation.md)",
        why_ja: r"汚染値が HTML sink に到達すると、パーサが見つけた script タグを実行する。DOM 層での XSS",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "client-env-public-leak",
        rule_id: Some(rule_id::CLIENT_ENV_PUBLIC_LEAK),
        severity: "High",
        description: r"`process.env.X` access inside a `'use client'` module (excluding `NEXT_PUBLIC_*` and the allow-list). Bundled to the browser by Next.js.",
        why: r"Next.js inlines `process.env.*` at build time; server-only secrets end up shipped inside the browser bundle",
        when_to_disable: None,
        description_ja: r"`'use client'` モジュール内での `process.env.X` 参照（`NEXT_PUBLIC_*` および allow-list は除外）。Next.js によりブラウザにバンドルされる",
        why_ja: r"Next.js は `process.env.*` を build 時にインライン化し、server 専用 secret がブラウザバンドルに同梱される",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "ssr-secret-bleed",
        rule_id: Some(rule_id::SSR_SECRET_BLEED),
        severity: "High",
        description: r"Prevents server-only secrets from leaking to the browser via SSR returns. Flags secret-named properties (`apiKey`, `token`, …) or `process.env.*` secret values returned from `getServerSideProps` / `'use server'` Server Actions, since Next.js serializes those returns into the client payload.",
        why: r"The SSR return is serialized into the HTML payload. Every visitor receives the secret, including the ones who never authenticate",
        when_to_disable: None,
        description_ja: r"`getServerSideProps` や `'use server'` Server Action が返す secret 名 (`apiKey`、`token`…) や `process.env.*` を flag。これらは Next.js がクライアントペイロードへシリアライズする",
        why_ja: r"SSR の返り値は HTML payload にシリアライズされ、認証していない訪問者を含む全員に secret が届く",
        when_to_disable_ja: None,
    },
    RuleDoc {
        table: Table::AstSecurity,
        key: "postmessage-origin-missing",
        rule_id: Some(rule_id::POSTMESSAGE_ORIGIN_MISSING),
        severity: "High",
        description: r"`window.addEventListener('message', handler)` whose inline handler never reads `event.origin`. Without an origin check, the page accepts cross-origin postMessages from arbitrary senders. External handler references and param-side destructure are out of scope (1-file static analysis).",
        why: r"Any embedded iframe or popup can send a message and the handler trusts it, so the page runs commands chosen by an attacker",
        when_to_disable: None,
        description_ja: r"`window.addEventListener('message', handler)` のインラインハンドラが `event.origin` を読まない場合。origin チェックなしでは任意の sender からのクロスオリジン postMessage を受け入れてしまう。外部ハンドラ参照やパラメータ側 destructure は 1-file static analysis の範囲外",
        why_ja: r"埋め込まれた iframe や popup から送られたメッセージをハンドラが信用し、ページが攻撃者の選んだコマンドを実行してしまう",
        when_to_disable_ja: None,
    },
];
